// Mocks generated by Mockito 5.4.6 from annotations
// in fleetmanager/test/provider/fleet_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:fleetmanager/models/enums/stato_veicolo.dart' as _i8;
import 'package:fleetmanager/models/manutenzione.dart' as _i12;
import 'package:fleetmanager/models/notifica.dart' as _i14;
import 'package:fleetmanager/models/prenotazione.dart' as _i10;
import 'package:fleetmanager/models/utente.dart' as _i5;
import 'package:fleetmanager/models/veicolo.dart' as _i7;
import 'package:fleetmanager/services/auth_service.dart' as _i3;
import 'package:fleetmanager/services/manutenzione_service.dart' as _i11;
import 'package:fleetmanager/services/notifica_service.dart' as _i13;
import 'package:fleetmanager/services/prenotazione_service.dart' as _i9;
import 'package:fleetmanager/services/veicolo_service.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i15;
import 'package:supabase_flutter/supabase_flutter.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGoTrueClient_0 extends _i1.SmartFake implements _i2.GoTrueClient {
  _FakeGoTrueClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFunctionsClient_1 extends _i1.SmartFake
    implements _i2.FunctionsClient {
  _FakeFunctionsClient_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSupabaseStorageClient_2 extends _i1.SmartFake
    implements _i2.SupabaseStorageClient {
  _FakeSupabaseStorageClient_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRealtimeClient_3 extends _i1.SmartFake
    implements _i2.RealtimeClient {
  _FakeRealtimeClient_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePostgrestClient_4 extends _i1.SmartFake
    implements _i2.PostgrestClient {
  _FakePostgrestClient_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSupabaseQueryBuilder_5 extends _i1.SmartFake
    implements _i2.SupabaseQueryBuilder {
  _FakeSupabaseQueryBuilder_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePostgrestFilterBuilder_6<T> extends _i1.SmartFake
    implements _i2.PostgrestFilterBuilder<T> {
  _FakePostgrestFilterBuilder_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRealtimeChannel_7 extends _i1.SmartFake
    implements _i2.RealtimeChannel {
  _FakeRealtimeChannel_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i3.AuthService {
  @override
  _i4.Future<_i5.Utente?> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
          ],
        ),
        returnValue: _i4.Future<_i5.Utente?>.value(),
        returnValueForMissingStub: _i4.Future<_i5.Utente?>.value(),
      ) as _i4.Future<_i5.Utente?>);

  @override
  _i4.Future<List<_i5.Utente>> getTuttiUtenti() => (super.noSuchMethod(
        Invocation.method(
          #getTuttiUtenti,
          [],
        ),
        returnValue: _i4.Future<List<_i5.Utente>>.value(<_i5.Utente>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i5.Utente>>.value(<_i5.Utente>[]),
      ) as _i4.Future<List<_i5.Utente>>);

  @override
  _i4.Future<_i5.Utente?> getUtenteByEmail(String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUtenteByEmail,
          [email],
        ),
        returnValue: _i4.Future<_i5.Utente?>.value(),
        returnValueForMissingStub: _i4.Future<_i5.Utente?>.value(),
      ) as _i4.Future<_i5.Utente?>);

  @override
  _i4.Future<bool> updateProfilo(_i5.Utente? u) => (super.noSuchMethod(
        Invocation.method(
          #updateProfilo,
          [u],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> createUtente(_i5.Utente? nuovoUtente) => (super.noSuchMethod(
        Invocation.method(
          #createUtente,
          [nuovoUtente],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> eliminaUtente(int? idUtente) => (super.noSuchMethod(
        Invocation.method(
          #eliminaUtente,
          [idUtente],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}

/// A class which mocks [VeicoloService].
///
/// See the documentation for Mockito's code generation for more information.
class MockVeicoloService extends _i1.Mock implements _i6.VeicoloService {
  @override
  _i4.Future<List<_i7.Veicolo>> fetchAllVeicoli() => (super.noSuchMethod(
        Invocation.method(
          #fetchAllVeicoli,
          [],
        ),
        returnValue: _i4.Future<List<_i7.Veicolo>>.value(<_i7.Veicolo>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i7.Veicolo>>.value(<_i7.Veicolo>[]),
      ) as _i4.Future<List<_i7.Veicolo>>);

  @override
  _i4.Future<void> updateStatoVeicolo(
    String? targa,
    _i8.StatoVeicolo? nuovoStato,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateStatoVeicolo,
          [
            targa,
            nuovoStato,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> createVeicolo(_i7.Veicolo? veicolo) => (super.noSuchMethod(
        Invocation.method(
          #createVeicolo,
          [veicolo],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i7.Veicolo?> getVeicoloByTarga(String? targa) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVeicoloByTarga,
          [targa],
        ),
        returnValue: _i4.Future<_i7.Veicolo?>.value(),
        returnValueForMissingStub: _i4.Future<_i7.Veicolo?>.value(),
      ) as _i4.Future<_i7.Veicolo?>);
}

/// A class which mocks [PrenotazioneService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPrenotazioneService extends _i1.Mock
    implements _i9.PrenotazioneService {
  @override
  _i4.Future<List<_i10.Prenotazione>> fetchPrenotazioni() =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchPrenotazioni,
          [],
        ),
        returnValue:
            _i4.Future<List<_i10.Prenotazione>>.value(<_i10.Prenotazione>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i10.Prenotazione>>.value(<_i10.Prenotazione>[]),
      ) as _i4.Future<List<_i10.Prenotazione>>);

  @override
  _i4.Future<void> creaPrenotazione(_i10.Prenotazione? p) =>
      (super.noSuchMethod(
        Invocation.method(
          #creaPrenotazione,
          [p],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> confermaPrenotazione(int? id) => (super.noSuchMethod(
        Invocation.method(
          #confermaPrenotazione,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> annullaPrenotazione(int? id) => (super.noSuchMethod(
        Invocation.method(
          #annullaPrenotazione,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> completaPrenotazione(int? id) => (super.noSuchMethod(
        Invocation.method(
          #completaPrenotazione,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> validaDisponibilita(
    String? targa,
    DateTime? inizio,
    DateTime? fine,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #validaDisponibilita,
          [
            targa,
            inizio,
            fine,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}

/// A class which mocks [ManutenzioneService].
///
/// See the documentation for Mockito's code generation for more information.
class MockManutenzioneService extends _i1.Mock
    implements _i11.ManutenzioneService {
  @override
  _i4.Future<void> registraIntervento(_i12.Manutenzione? m) =>
      (super.noSuchMethod(
        Invocation.method(
          #registraIntervento,
          [m],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> chiudiIntervento(
    int? id,
    int? kmFinali,
    String? targa,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #chiudiIntervento,
          [
            id,
            kmFinali,
            targa,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i12.Manutenzione>> fetchTutte() => (super.noSuchMethod(
        Invocation.method(
          #fetchTutte,
          [],
        ),
        returnValue:
            _i4.Future<List<_i12.Manutenzione>>.value(<_i12.Manutenzione>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i12.Manutenzione>>.value(<_i12.Manutenzione>[]),
      ) as _i4.Future<List<_i12.Manutenzione>>);

  @override
  _i4.Future<void> segnalareInterventoStraordinario(
    String? targa,
    String? descrizione,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #segnalareInterventoStraordinario,
          [
            targa,
            descrizione,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateManutenzione(
    int? id,
    Map<String, dynamic>? dati,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateManutenzione,
          [
            id,
            dati,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [NotificaService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificaService extends _i1.Mock implements _i13.NotificaService {
  @override
  _i4.Future<List<_i14.Notifica>> fetchMieNotifiche(int? idUtente) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchMieNotifiche,
          [idUtente],
        ),
        returnValue: _i4.Future<List<_i14.Notifica>>.value(<_i14.Notifica>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i14.Notifica>>.value(<_i14.Notifica>[]),
      ) as _i4.Future<List<_i14.Notifica>>);

  @override
  _i4.Future<void> segnaLetta(int? id) => (super.noSuchMethod(
        Invocation.method(
          #segnaLetta,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> inviaNotificaScadenza(
    int? idManager,
    int? idScadenza,
    String? targa,
    String? tipoScadenza,
    DateTime? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #inviaNotificaScadenza,
          [
            idManager,
            idScadenza,
            targa,
            tipoScadenza,
            data,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> notificaRichiestaPrenotazione(
    int? idUtenteDestinatario,
    String? nomeDriver,
    String? targa,
    DateTime? inizio,
    DateTime? fine,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #notificaRichiestaPrenotazione,
          [
            idUtenteDestinatario,
            nomeDriver,
            targa,
            inizio,
            fine,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> notificaConfermaPrenotazione(
    int? idDriver,
    String? targa,
    DateTime? dataInizio,
    DateTime? dataFine,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #notificaConfermaPrenotazione,
          [
            idDriver,
            targa,
            dataInizio,
            dataFine,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> notificaRifiutoPrenotazione(
    int? idDriver,
    String? targa,
    DateTime? dataInizio,
    DateTime? dataFine,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #notificaRifiutoPrenotazione,
          [
            idDriver,
            targa,
            dataInizio,
            dataFine,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> notificaManutenzioneProgrammata(
    int? idUtente,
    String? targa,
    DateTime? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #notificaManutenzioneProgrammata,
          [
            idUtente,
            targa,
            data,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> notificaAnnullamentoPrenotazioneDaDriver(
    int? idManager,
    int? idDriver,
    String? targa,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #notificaAnnullamentoPrenotazioneDaDriver,
          [
            idManager,
            idDriver,
            targa,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> notificaInterventoStraordinario(
    int? idManager,
    String? targa,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #notificaInterventoStraordinario,
          [
            idManager,
            targa,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> eliminaNotifica(int? id) => (super.noSuchMethod(
        Invocation.method(
          #eliminaNotifica,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> svuotaNotifiche(int? idUtente) => (super.noSuchMethod(
        Invocation.method(
          #svuotaNotifiche,
          [idUtente],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [SupabaseClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseClient extends _i1.Mock implements _i2.SupabaseClient {
  @override
  String get supabaseUrl => (super.noSuchMethod(
        Invocation.getter(#supabaseUrl),
        returnValue: _i15.dummyValue<String>(
          this,
          Invocation.getter(#supabaseUrl),
        ),
        returnValueForMissingStub: _i15.dummyValue<String>(
          this,
          Invocation.getter(#supabaseUrl),
        ),
      ) as String);

  @override
  String get supabaseKey => (super.noSuchMethod(
        Invocation.getter(#supabaseKey),
        returnValue: _i15.dummyValue<String>(
          this,
          Invocation.getter(#supabaseKey),
        ),
        returnValueForMissingStub: _i15.dummyValue<String>(
          this,
          Invocation.getter(#supabaseKey),
        ),
      ) as String);

  @override
  String get schema => (super.noSuchMethod(
        Invocation.getter(#schema),
        returnValue: _i15.dummyValue<String>(
          this,
          Invocation.getter(#schema),
        ),
        returnValueForMissingStub: _i15.dummyValue<String>(
          this,
          Invocation.getter(#schema),
        ),
      ) as String);

  @override
  String get restUrl => (super.noSuchMethod(
        Invocation.getter(#restUrl),
        returnValue: _i15.dummyValue<String>(
          this,
          Invocation.getter(#restUrl),
        ),
        returnValueForMissingStub: _i15.dummyValue<String>(
          this,
          Invocation.getter(#restUrl),
        ),
      ) as String);

  @override
  String get realtimeUrl => (super.noSuchMethod(
        Invocation.getter(#realtimeUrl),
        returnValue: _i15.dummyValue<String>(
          this,
          Invocation.getter(#realtimeUrl),
        ),
        returnValueForMissingStub: _i15.dummyValue<String>(
          this,
          Invocation.getter(#realtimeUrl),
        ),
      ) as String);

  @override
  String get authUrl => (super.noSuchMethod(
        Invocation.getter(#authUrl),
        returnValue: _i15.dummyValue<String>(
          this,
          Invocation.getter(#authUrl),
        ),
        returnValueForMissingStub: _i15.dummyValue<String>(
          this,
          Invocation.getter(#authUrl),
        ),
      ) as String);

  @override
  String get storageUrl => (super.noSuchMethod(
        Invocation.getter(#storageUrl),
        returnValue: _i15.dummyValue<String>(
          this,
          Invocation.getter(#storageUrl),
        ),
        returnValueForMissingStub: _i15.dummyValue<String>(
          this,
          Invocation.getter(#storageUrl),
        ),
      ) as String);

  @override
  String get functionsUrl => (super.noSuchMethod(
        Invocation.getter(#functionsUrl),
        returnValue: _i15.dummyValue<String>(
          this,
          Invocation.getter(#functionsUrl),
        ),
        returnValueForMissingStub: _i15.dummyValue<String>(
          this,
          Invocation.getter(#functionsUrl),
        ),
      ) as String);

  @override
  _i2.GoTrueClient get auth => (super.noSuchMethod(
        Invocation.getter(#auth),
        returnValue: _FakeGoTrueClient_0(
          this,
          Invocation.getter(#auth),
        ),
        returnValueForMissingStub: _FakeGoTrueClient_0(
          this,
          Invocation.getter(#auth),
        ),
      ) as _i2.GoTrueClient);

  @override
  _i2.FunctionsClient get functions => (super.noSuchMethod(
        Invocation.getter(#functions),
        returnValue: _FakeFunctionsClient_1(
          this,
          Invocation.getter(#functions),
        ),
        returnValueForMissingStub: _FakeFunctionsClient_1(
          this,
          Invocation.getter(#functions),
        ),
      ) as _i2.FunctionsClient);

  @override
  _i2.SupabaseStorageClient get storage => (super.noSuchMethod(
        Invocation.getter(#storage),
        returnValue: _FakeSupabaseStorageClient_2(
          this,
          Invocation.getter(#storage),
        ),
        returnValueForMissingStub: _FakeSupabaseStorageClient_2(
          this,
          Invocation.getter(#storage),
        ),
      ) as _i2.SupabaseStorageClient);

  @override
  _i2.RealtimeClient get realtime => (super.noSuchMethod(
        Invocation.getter(#realtime),
        returnValue: _FakeRealtimeClient_3(
          this,
          Invocation.getter(#realtime),
        ),
        returnValueForMissingStub: _FakeRealtimeClient_3(
          this,
          Invocation.getter(#realtime),
        ),
      ) as _i2.RealtimeClient);

  @override
  _i2.PostgrestClient get rest => (super.noSuchMethod(
        Invocation.getter(#rest),
        returnValue: _FakePostgrestClient_4(
          this,
          Invocation.getter(#rest),
        ),
        returnValueForMissingStub: _FakePostgrestClient_4(
          this,
          Invocation.getter(#rest),
        ),
      ) as _i2.PostgrestClient);

  @override
  Map<String, String> get headers => (super.noSuchMethod(
        Invocation.getter(#headers),
        returnValue: <String, String>{},
        returnValueForMissingStub: <String, String>{},
      ) as Map<String, String>);

  @override
  set auth(_i2.GoTrueClient? value) => super.noSuchMethod(
        Invocation.setter(
          #auth,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set functions(_i2.FunctionsClient? value) => super.noSuchMethod(
        Invocation.setter(
          #functions,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set storage(_i2.SupabaseStorageClient? value) => super.noSuchMethod(
        Invocation.setter(
          #storage,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set realtime(_i2.RealtimeClient? value) => super.noSuchMethod(
        Invocation.setter(
          #realtime,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set rest(_i2.PostgrestClient? value) => super.noSuchMethod(
        Invocation.setter(
          #rest,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set headers(Map<String, String>? headers) => super.noSuchMethod(
        Invocation.setter(
          #headers,
          headers,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.SupabaseQueryBuilder from(String? table) => (super.noSuchMethod(
        Invocation.method(
          #from,
          [table],
        ),
        returnValue: _FakeSupabaseQueryBuilder_5(
          this,
          Invocation.method(
            #from,
            [table],
          ),
        ),
        returnValueForMissingStub: _FakeSupabaseQueryBuilder_5(
          this,
          Invocation.method(
            #from,
            [table],
          ),
        ),
      ) as _i2.SupabaseQueryBuilder);

  @override
  _i2.PostgrestClient useSchema(String? schema) => (super.noSuchMethod(
        Invocation.method(
          #useSchema,
          [schema],
        ),
        returnValue: _FakePostgrestClient_4(
          this,
          Invocation.method(
            #useSchema,
            [schema],
          ),
        ),
        returnValueForMissingStub: _FakePostgrestClient_4(
          this,
          Invocation.method(
            #useSchema,
            [schema],
          ),
        ),
      ) as _i2.PostgrestClient);

  @override
  _i2.PostgrestFilterBuilder<dynamic> rpc(
    String? fn, {
    Map<String, dynamic>? params,
    _i2.FetchOptions? options = const _i2.FetchOptions(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #rpc,
          [fn],
          {
            #params: params,
            #options: options,
          },
        ),
        returnValue: _FakePostgrestFilterBuilder_6<dynamic>(
          this,
          Invocation.method(
            #rpc,
            [fn],
            {
              #params: params,
              #options: options,
            },
          ),
        ),
        returnValueForMissingStub: _FakePostgrestFilterBuilder_6<dynamic>(
          this,
          Invocation.method(
            #rpc,
            [fn],
            {
              #params: params,
              #options: options,
            },
          ),
        ),
      ) as _i2.PostgrestFilterBuilder<dynamic>);

  @override
  _i2.RealtimeChannel channel(
    String? name, {
    _i2.RealtimeChannelConfig? opts = const _i2.RealtimeChannelConfig(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #channel,
          [name],
          {#opts: opts},
        ),
        returnValue: _FakeRealtimeChannel_7(
          this,
          Invocation.method(
            #channel,
            [name],
            {#opts: opts},
          ),
        ),
        returnValueForMissingStub: _FakeRealtimeChannel_7(
          this,
          Invocation.method(
            #channel,
            [name],
            {#opts: opts},
          ),
        ),
      ) as _i2.RealtimeChannel);

  @override
  List<_i2.RealtimeChannel> getChannels() => (super.noSuchMethod(
        Invocation.method(
          #getChannels,
          [],
        ),
        returnValue: <_i2.RealtimeChannel>[],
        returnValueForMissingStub: <_i2.RealtimeChannel>[],
      ) as List<_i2.RealtimeChannel>);

  @override
  _i4.Future<String> removeChannel(_i2.RealtimeChannel? channel) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeChannel,
          [channel],
        ),
        returnValue: _i4.Future<String>.value(_i15.dummyValue<String>(
          this,
          Invocation.method(
            #removeChannel,
            [channel],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<String>.value(_i15.dummyValue<String>(
          this,
          Invocation.method(
            #removeChannel,
            [channel],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<List<String>> removeAllChannels() => (super.noSuchMethod(
        Invocation.method(
          #removeAllChannels,
          [],
        ),
        returnValue: _i4.Future<List<String>>.value(<String>[]),
        returnValueForMissingStub: _i4.Future<List<String>>.value(<String>[]),
      ) as _i4.Future<List<String>>);

  @override
  _i4.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
