name: Deploy to GitHub Pages

on:
  push:
    branches:
      - develop

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get dependencies
        working-directory: fleetmanager
        run: flutter pub get

      - name: Build Web
        working-directory: fleetmanager
        run: flutter build web --release --base-href "/FleetManagerFlutter/"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: fleetmanager/build/web
          branch: gh-pages
