name: fleetmanager
description: "A new Flutter project for fleet management."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' 

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.6.0
  image_picker: ^1.0.7
  fl_chart: ^0.66.0  

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  intl: any
  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # Pacchetto per generare le icone
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # Registrazione dell'immagine per l'app
  assets:
    - assets/images/app_icon.png

# Configurazione specifica per la generazione delle icone Android e iOS
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  windows:
    generate: true
    icon_size: 256
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#1565C0"
  adaptive_icon_foreground: "assets/images/app_icon.png"