name: Deploy to GitHub Pages

on:
  push:
    branches:
      - develop  # Questo dice a GitHub: "Ogni volta che fcio push su develop, lavora"

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build Web
        run: |
          flutter pub get
          flutter build web --release --base-href "/FleetManagerFlutter/"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/web
          branch: gh-pages